import { useState } from "react";
import { Navbar } from "../../components/Navbar";

const initialPrescriptions = [
  { id: 1, name: "Atorvastatin", dosage: "20mg", frequency: "Once daily", refillsLeft: 3, quantityLeft: 28, totalQuantity: 30, doctor: "Dr. Sarah Mitchell", prescribed: "Jan 15, 2026", category: "Cardiovascular", active: true },
  { id: 2, name: "Metformin", dosage: "500mg", frequency: "Twice daily", refillsLeft: 5, quantityLeft: 12, totalQuantity: 60, doctor: "Dr. James Patel", prescribed: "Dec 20, 2025", category: "Diabetes", active: true },
  { id: 3, name: "Lisinopril", dosage: "10mg", frequency: "Once daily", refillsLeft: 0, quantityLeft: 4, totalQuantity: 30, doctor: "Dr. Sarah Mitchell", prescribed: "Nov 10, 2025", category: "Blood Pressure", active: true },
  { id: 4, name: "Amoxicillin", dosage: "250mg", frequency: "Three times daily", refillsLeft: 0, quantityLeft: 0, totalQuantity: 21, doctor: "Dr. James Patel", prescribed: "Oct 5, 2025", category: "Antibiotic", active: false },
  { id: 5, name: "Cetirizine", dosage: "10mg", frequency: "Once daily (as needed)", refillsLeft: 2, quantityLeft: 20, totalQuantity: 30, doctor: "Dr. Lena Horowitz", prescribed: "Jan 28, 2026", category: "Allergy", active: true },
];

const categoryColors = {
  Cardiovascular: { bg: "rgba(59,130,246,0.12)", text: "#60a5fa", border: "rgba(59,130,246,0.25)" },
  Diabetes: { bg: "rgba(16,185,129,0.12)", text: "#34d399", border: "rgba(16,185,129,0.25)" },
  "Blood Pressure": { bg: "rgba(245,158,11,0.12)", text: "#fbbf24", border: "rgba(245,158,11,0.25)" },
  Antibiotic: { bg: "rgba(239,68,68,0.12)", text: "#f87171", border: "rgba(239,68,68,0.25)" },
  Allergy: { bg: "rgba(139,92,246,0.12)", text: "#a78bfa", border: "rgba(139,92,246,0.25)" },
};

export const Prescriptions = () => {
  const [prescriptions, setPrescriptions] = useState(initialPrescriptions);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  const [toast, setToast] = useState(null);
  const [refillRequested, setRefillRequested] = useState({});

  const showToast = (msg, type = "success") => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 3000);
  };

  const handleRefill = (id) => {
    setRefillRequested(p => ({ ...p, [id]: true }));
    showToast("Refill request sent to your doctor!");
  };

  const handleDownload = (rx) => {
    const content = `HEALIX — Prescription Details\n${"─".repeat(40)}\nMedication : ${rx.name} ${rx.dosage}\nFrequency  : ${rx.frequency}\nPrescribed : ${rx.prescribed}\nDoctor     : ${rx.doctor}\nCategory   : ${rx.category}\nRefills    : ${rx.refillsLeft} remaining\nQuantity   : ${rx.quantityLeft} / ${rx.totalQuantity} left\n${"─".repeat(40)}\nGenerated by HEALIX on ${new Date().toLocaleDateString()}`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${rx.name}_prescription.txt`; a.click();
    URL.revokeObjectURL(url);
    showToast(`Downloaded ${rx.name} prescription.`);
  };

  const filtered = prescriptions.filter(rx => {
    const matchSearch = rx.name.toLowerCase().includes(search.toLowerCase()) || rx.category.toLowerCase().includes(search.toLowerCase()) || rx.doctor.toLowerCase().includes(search.toLowerCase());
    const matchFilter = filter === "all" || (filter === "active" && rx.active) || (filter === "inactive" && !rx.active) || (filter === "refill" && rx.refillsLeft === 0 && rx.active);
    return matchSearch && matchFilter;
  });

  const getQuantityColor = (left, total) => {
    const pct = left / total;
    if (pct > 0.5) return "#10b981";
    if (pct > 0.2) return "#f59e0b";
    return "#ef4444";
  };

  return (
    <>
      <Navbar />
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600&display=swap');
        @keyframes fadeUp { from { opacity:0; transform:translateY(16px);} to { opacity:1; transform:translateY(0);} }
        @keyframes toastIn { from { opacity:0; transform:translateY(20px);} to { opacity:1; transform:translateY(0);} }
        .rx-card { transition: transform 0.18s ease, box-shadow 0.18s ease; }
        .rx-card:hover { transform: translateY(-3px); box-shadow: 0 12px 32px rgba(0,0,0,0.35) !important; }
        .rx-btn { transition: all 0.15s ease; cursor: pointer; }
        .rx-btn:hover { opacity: 0.85; transform: translateY(-1px); }
        .search-input { background: #0f172a; border: 1px solid #1e293b; color: #f1f5f9; padding: 11px 16px 11px 42px; border-radius: 10px; font-size: 14px; outline: none; font-family: 'DM Sans', sans-serif; width: 280px; box-sizing: border-box; transition: border-color 0.2s; }
        .search-input:focus { border-color: #3b82f6; }
        .search-input::placeholder { color: #334155; }
        .filter-btn { padding: 8px 18px; border-radius: 8px; border: none; font-weight: 600; font-size: 13px; cursor: pointer; transition: all 0.15s ease; font-family: 'DM Sans', sans-serif; }
      `}</style>

      <div style={{ background: "#060d1a", minHeight: "100vh", padding: "40px 48px", fontFamily: "'DM Sans', sans-serif" }}>

        {/* Toast */}
        {toast && (
          <div style={{ position:"fixed", bottom:"32px", right:"32px", zIndex:2000, background: toast.type==="error" ? "#ef4444" : "#10b981", color:"#fff", padding:"12px 24px", borderRadius:"10px", fontWeight:"600", fontSize:"14px", animation:"toastIn 0.3s ease", boxShadow:"0 8px 24px rgba(0,0,0,0.3)" }}>
            {toast.msg}
          </div>
        )}

        {/* Header */}
        <div style={{ marginBottom:"36px", animation:"fadeUp 0.5s ease both" }}>
          <p style={{ color:"#10b981", fontSize:"12px", fontWeight:"600", letterSpacing:"2px", textTransform:"uppercase", margin:"0 0 6px 0" }}>Healthcare</p>
          <h1 style={{ color:"#f1f5f9", fontSize:"32px", fontWeight:"700", margin:0, fontFamily:"'Playfair Display', serif", letterSpacing:"-0.5px" }}>Prescriptions</h1>
        </div>

        {/* Stats Row */}
        <div style={{ display:"grid", gridTemplateColumns:"repeat(3, 1fr)", gap:"16px", marginBottom:"32px", animation:"fadeUp 0.5s ease 0.08s both" }}>
          {[
            { label:"Active Medicines", value: prescriptions.filter(r=>r.active).length, color:"#3b82f6" },
            { label:"Refills Needed", value: prescriptions.filter(r=>r.refillsLeft===0 && r.active).length, color:"#f59e0b" },
            { label:"Total Prescriptions", value: prescriptions.length, color:"#10b981" },
          ].map((s, i) => (
            <div key={i} style={{ background:"#0f172a", border:"1px solid #1e293b", borderRadius:"14px", padding:"20px 24px" }}>
              <div style={{ color:s.color, fontSize:"28px", fontWeight:"700", marginBottom:"4px" }}>{s.value}</div>
              <div style={{ color:"#64748b", fontSize:"13px", fontWeight:"500" }}>{s.label}</div>
            </div>
          ))}
        </div>

        {/* Search + Filter */}
        <div style={{ display:"flex", gap:"12px", alignItems:"center", marginBottom:"28px", flexWrap:"wrap", animation:"fadeUp 0.5s ease 0.12s both" }}>
          <div style={{ position:"relative" }}>
            <span style={{ position:"absolute", left:"14px", top:"50%", transform:"translateY(-50%)", fontSize:"16px", pointerEvents:"none" }}>🔍</span>
            <input type="text" placeholder="Search prescriptions..." className="search-input" value={search} onChange={e => setSearch(e.target.value)} />
          </div>
          <div style={{ display:"flex", gap:"6px" }}>
            {[["all","All"],["active","Active"],["inactive","Inactive"],["refill","Needs Refill"]].map(([val, label]) => (
              <button key={val} className="filter-btn" onClick={() => setFilter(val)}
                style={{ background: filter===val ? "#3b82f6" : "#0f172a", color: filter===val ? "#fff" : "#64748b", border: filter===val ? "none" : "1px solid #1e293b" }}>
                {label}
              </button>
            ))}
          </div>
        </div>

        {/* Prescription Cards */}
        <div style={{ display:"flex", flexDirection:"column", gap:"16px" }}>
          {filtered.length === 0 && (
            <div style={{ textAlign:"center", color:"#334155", padding:"60px", fontSize:"16px" }}>No prescriptions found.</div>
          )}
          {filtered.map((rx, i) => {
            const cat = categoryColors[rx.category] || categoryColors.Antibiotic;
            const qtyColor = getQuantityColor(rx.quantityLeft, rx.totalQuantity);
            const qtyPct = Math.round((rx.quantityLeft / rx.totalQuantity) * 100);
            return (
              <div key={rx.id} className="rx-card" style={{ background:"#0f172a", border:"1px solid #1e293b", borderRadius:"14px", padding:"24px", animation:`fadeUp 0.4s ease ${i*0.06}s both`, boxShadow:"0 2px 12px rgba(0,0,0,0.2)", opacity: rx.active ? 1 : 0.6 }}>
                <div style={{ display:"flex", alignItems:"flex-start", gap:"20px" }}>
                  {/* Left */}
                  <div style={{ flex:1 }}>
                    <div style={{ display:"flex", alignItems:"center", gap:"12px", marginBottom:"8px", flexWrap:"wrap" }}>
                      <span style={{ color:"#f1f5f9", fontWeight:"700", fontSize:"18px" }}>{rx.name}</span>
                      <span style={{ color:"#94a3b8", fontSize:"14px", fontWeight:"500" }}>{rx.dosage}</span>
                      <span style={{ padding:"3px 10px", borderRadius:"20px", fontSize:"11px", fontWeight:"700", background:cat.bg, color:cat.text, border:`1px solid ${cat.border}`, letterSpacing:"0.3px" }}>{rx.category}</span>
                      {!rx.active && <span style={{ padding:"3px 10px", borderRadius:"20px", fontSize:"11px", fontWeight:"700", background:"rgba(71,85,105,0.2)", color:"#64748b", border:"1px solid #1e293b" }}>Inactive</span>}
                    </div>
                    <div style={{ color:"#64748b", fontSize:"13px", marginBottom:"16px" }}>
                      {rx.frequency} · Prescribed by {rx.doctor} on {rx.prescribed}
                    </div>

                    {/* Quantity bar */}
                    <div style={{ marginBottom:"8px" }}>
                      <div style={{ display:"flex", justifyContent:"space-between", marginBottom:"6px" }}>
                        <span style={{ color:"#64748b", fontSize:"12px", fontWeight:"600", textTransform:"uppercase", letterSpacing:"0.5px" }}>Quantity Left</span>
                        <span style={{ color:qtyColor, fontSize:"12px", fontWeight:"700" }}>{rx.quantityLeft} / {rx.totalQuantity} tablets</span>
                      </div>
                      <div style={{ height:"6px", background:"#1e293b", borderRadius:"99px", overflow:"hidden" }}>
                        <div style={{ height:"100%", width:`${qtyPct}%`, background:qtyColor, borderRadius:"99px", transition:"width 0.5s ease" }} />
                      </div>
                    </div>

                    {/* Refills */}
                    <div style={{ display:"flex", alignItems:"center", gap:"8px", marginTop:"10px" }}>
                      <span style={{ color:"#64748b", fontSize:"13px" }}>Refills remaining:</span>
                      <span style={{ color: rx.refillsLeft === 0 ? "#ef4444" : "#10b981", fontWeight:"700", fontSize:"14px" }}>
                        {rx.refillsLeft === 0 ? "None — Refill needed" : rx.refillsLeft}
                      </span>
                    </div>
                  </div>

                  {/* Right — Action buttons */}
                  {rx.active && (
                    <div style={{ display:"flex", flexDirection:"column", gap:"10px", flexShrink:0 }}>
                      <button className="rx-btn" onClick={() => handleRefill(rx.id)}
                        disabled={refillRequested[rx.id]}
                        style={{ padding:"9px 18px", borderRadius:"8px", border:"none", background: refillRequested[rx.id] ? "#1e293b" : "#3b82f6", color: refillRequested[rx.id] ? "#64748b" : "#fff", fontWeight:"600", fontSize:"13px", fontFamily:"'DM Sans',sans-serif", whiteSpace:"nowrap" }}>
                        {refillRequested[rx.id] ? "✓ Requested" : "Request Refill"}
                      </button>
                      <button className="rx-btn" onClick={() => handleDownload(rx)}
                        style={{ padding:"9px 18px", borderRadius:"8px", border:"1px solid #1e293b", background:"transparent", color:"#94a3b8", fontWeight:"600", fontSize:"13px", fontFamily:"'DM Sans',sans-serif", whiteSpace:"nowrap" }}>
                        ↓ Download
                      </button>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
};
